### ISSUE TITLE
Batch management issues

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#375]
* [x] Limit inspector's list to user from accessible department. #371
* [x] Stop loading all building, then filtering the list to display only those from the batch. #373
* [x] Transform building searchable list into a grid so it's easier to search. #327
* [x] Fix 'batîment' grammar error. #327
* [ ] Add waitform? **so much faster now that #373 is done that it's not necessary**  #327
* [x] Check if inspector loading time is long. #327
* [ ] Check if there is a problem when saving without having checked ready for inspection. **non répété**  #360
