### ISSUE TITLE
Reporting issues

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip#514]
Report editor: 
* [x] Missing fields in BuildingHazardousMaterial (#504)
* [x] Check if we can have shorter property name.

Report generation:
* [x] Changer la partie "questionnaire".  Les headers en gras et le reste sans style particulier.  Le tableau sera 100% width au lieu d'une taille fixe. (#495)

Dashboard:
* [x] Le rapport ne sort pas quand il a eu plus d'une inspection. (#503)

**Comment by iamkinetic** [comment]
@jocelyncardinal En changeant le nom des champs, tu auras nécessairement des "breaking changes" dans tes rapports.  Je te mettrai les correspondances ici.

**Comment by iamkinetic** [comment]
@jocelyncardinal

HazardousMaterialName => MaterialName
HazardousMaterialNumber => MaterialNumber
QuantityDescription n'existera plus.  Il y aura maintenant les champs séparés (Quantity, UnitOfMeasure).

**Comment by iamkinetic** [comment]
@philipperobertgh 
Au testeur : À noter que le dernier sous-point n'était pas un bug dans mes tests.
